<html>
	<head>
		<title>Login Page</title>
		<!--<link rel="stylesheet" href="/css/login.css" type="text/css" >-->
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	</head>
	<body>
	<div class="container" align="center">
	
	<div class="well"><h2><b>Employee Asset Form<b><h2></div>
	</div>
	<div class="container" align="center">
	<div class="jumbotron">
		<!-- to display login page-->
		<?php  echo  $this->employee;  ?>
	
	</body>
</html>